### ISSUE TITLE
 [vm-other]

### ISSUE THREAD

**Issue by cskimpel** [SoftwareEngineeringToolDemos/ICSE-2010-ConQat#5]
MP4 Driver not installed on VM. When I opened the desktop demonstration video, a driver was download but I was unable to install it, because it prompted for an administrator password.

I did not have an administrator password, due to the auto login. (Video was however also on utube and a link was provided to view it on utube).

**Comment by vinay92** [comment]
Since the assignment specification was to have a link for the video, I did not install the drivers on the VM. The video is just meant to be a backup to the youtube link. Its better not to install unnecessary software.
